### get all notes
GET http://localhost:3003/api/persons

### create new note
POST http://localhost:3003/api/persons
Content-Type: application/json

{
  "name": "Postman test",
  "number": "3124423"
}

### create new note empty
POST http://localhost:3003/api/persons
Content-Type: application/json


### delete note by id
DELETE http://localhost:3003/api/persons/2

### get main
GET http://localhost:3003

### update
PUT http://localhost:3003/api/persons/6688192fc000d296ffff4506
Content-Type: application/json

{
  "name": "dsdsds",
  "number": "1111"
}

### get by id
GET http://localhost:3003/api/persons/6688192fc000d296ffff4506